# Generated by Django 4.1 on 2023-03-08 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='time_slots_ids',
            new_name='time_slot_ids',
        ),
    ]
