# Generated by Django 4.0.3 on 2022-05-23 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='rooms_available',
            new_name='room_available',
        ),
    ]
