# Generated by Django 4.0.3 on 2022-06-22 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_name',
            new_name='desired_username',
        ),
    ]
