# Generated by Django 4.1 on 2022-12-05 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='room_number',
            new_name='room',
        ),
    ]
