# Generated by Django 4.0.3 on 2022-06-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomavailable',
            name='available_from',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='roomavailable',
            name='available_till',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
