# Generated by Django 4.1 on 2022-11-20 17:48

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_room_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room_numbers',
            field=models.CharField(max_length=4000, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\ ,\\d+)*\\Z'), code='invalid', message=None)]),
        ),
    ]
