# Generated by Django 4.0.3 on 2022-05-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_rename_rooms_available_timeslot_room_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='room_available',
            field=models.TimeField(),
        ),
    ]
