# Generated by Django 4.1 on 2022-09-26 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_booking_no_of_rooms_alter_booking_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='person',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)]),
        ),
    ]
