# Generated by Django 4.0.3 on 2022-08-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_remove_customer_id_remove_room_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAPI',
            fields=[
                ('desired_username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=120)),
                ('confirm_password', models.CharField(max_length=120)),
            ],
        ),
    ]
