# Generated by Django 4.1 on 2022-12-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_room_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='advance',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
