# Generated by Django 4.1 on 2022-12-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_rename_room_number_timeslot_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
