# Generated by Django 4.1 on 2023-03-08 14:14

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_rename_time_slots_ids_booking_time_slot_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time_slot_ids',
            field=models.CharField(max_length=4000, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\ \\d+)*\\Z'), code='invalid', message=None)]),
        ),
    ]
