# Generated by Django 4.0.3 on 2022-06-11 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_roomavailable_available_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomavailable',
            name='available_from',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='roomavailable',
            name='available_till',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
