# Generated by Django 4.1 on 2022-09-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_booking_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='person',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=2),
        ),
    ]
