# Generated by Django 4.1 on 2023-01-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_room_advance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['number']},
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_manager',
            new_name='manager',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_number',
            new_name='number',
        ),
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Executive', 'Executive')], default='Regular', max_length=9),
        ),
    ]
