# Generated by Django 4.0.3 on 2022-06-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_customer_capacity_alter_room_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='capacity',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=3),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=3),
        ),
    ]
