# Generated by Django 4.1 on 2022-10-20 17:43

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_booking_no_of_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='no_of_rooms',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_number',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
